% Takes LabeledFlyStruct and turns it into a matrix of features (GLM_Input_Mat)
% and a response vector (GLM_Resp_Vec)

GLM_Input_Struct = struct();

[NumFlies, MinFlips] = size(LabelOrder);
NumFlies = NumFlies/2;
numFlipsLabeled = progInLabel - 1;
GLM_struct_counter = 1;

% imshow(imread('IsoD1_BC_training_bg_flip1.png'))
% [x_cent_corr_odd, y_cent_corr_odd] = ginput(7);
% imshow(imread('IsoD1_BC_training_bg_flip2.png'))
% [x_cent_corr_even, y_cent_corr_even] = ginput(7);

for flyCounter = 1:NumFlies
    for flipCounter = 1:numFlipsLabeled
    
        GLM_Input_Struct(GLM_struct_counter).Area = ...
             LabeledFlyStruct.ExpNum(flyCounter).BehavData.OddFlips(LabelOrder(flyCounter,flipCounter)).Area;
        GLM_Input_Struct(GLM_struct_counter).CentroidX = ...
             LabeledFlyStruct.ExpNum(flyCounter).BehavData.OddFlips(LabelOrder(flyCounter,flipCounter)).CentroidX - ...
             x_cent_corr_odd(flyCounter);
        GLM_Input_Struct(GLM_struct_counter).CentroidY = ...
             LabeledFlyStruct.ExpNum(flyCounter).BehavData.OddFlips(LabelOrder(flyCounter,flipCounter)).CentroidY - ...
             y_cent_corr_odd(flyCounter);
        GLM_Input_Struct(GLM_struct_counter).BoundingBoxTLX = ...
             LabeledFlyStruct.ExpNum(flyCounter).BehavData.OddFlips(LabelOrder(flyCounter,flipCounter)).BoundingBoxTLX - ...
             x_cent_corr_odd(flyCounter);
        GLM_Input_Struct(GLM_struct_counter).BoundingBoxTLY = ...
             LabeledFlyStruct.ExpNum(flyCounter).BehavData.OddFlips(LabelOrder(flyCounter,flipCounter)).BoundingBoxTLY - ...
             y_cent_corr_odd(flyCounter);
        GLM_Input_Struct(GLM_struct_counter).BoundingBoxWidth = ...
             LabeledFlyStruct.ExpNum(flyCounter).BehavData.OddFlips(LabelOrder(flyCounter,flipCounter)).BoundingBoxWidth;
        GLM_Input_Struct(GLM_struct_counter).BoundingBoxHeight = ...
             LabeledFlyStruct.ExpNum(flyCounter).BehavData.OddFlips(LabelOrder(flyCounter,flipCounter)).BoundingBoxHeight;
        GLM_Input_Struct(GLM_struct_counter).MajorAxisLength = ...
             LabeledFlyStruct.ExpNum(flyCounter).BehavData.OddFlips(LabelOrder(flyCounter,flipCounter)).MajorAxisLength;
        GLM_Input_Struct(GLM_struct_counter).MinorAxisLength = ...
             LabeledFlyStruct.ExpNum(flyCounter).BehavData.OddFlips(LabelOrder(flyCounter,flipCounter)).MinorAxisLength;
        GLM_Input_Struct(GLM_struct_counter).Circularity = ...
             LabeledFlyStruct.ExpNum(flyCounter).BehavData.OddFlips(LabelOrder(flyCounter,flipCounter)).Circularity;
        GLM_Input_Struct(GLM_struct_counter).Orientation = ...
             LabeledFlyStruct.ExpNum(flyCounter).BehavData.OddFlips(LabelOrder(flyCounter,flipCounter)).Orientation;
        GLM_Input_Struct(GLM_struct_counter).VelX = ...
             LabeledFlyStruct.ExpNum(flyCounter).BehavData.OddFlips(LabelOrder(flyCounter,flipCounter)).VelX;
        GLM_Input_Struct(GLM_struct_counter).VelY = ...
             LabeledFlyStruct.ExpNum(flyCounter).BehavData.OddFlips(LabelOrder(flyCounter,flipCounter)).VelY;
        GLM_Input_Struct(GLM_struct_counter).Speed = ...
             LabeledFlyStruct.ExpNum(flyCounter).BehavData.OddFlips(LabelOrder(flyCounter,flipCounter)).Speed;
        GLM_Input_Struct(GLM_struct_counter).AngularSpeed = ...
             LabeledFlyStruct.ExpNum(flyCounter).BehavData.OddFlips(LabelOrder(flyCounter,flipCounter)).AngularSpeed;
        GLM_Input_Struct(GLM_struct_counter).InGapRegionYN = ...
             ((LabeledFlyStruct.ExpNum(flyCounter).BehavData.OddFlips(LabelOrder(flyCounter,flipCounter)).CompID == 2) + ...
             (LabeledFlyStruct.ExpNum(flyCounter).BehavData.OddFlips(LabelOrder(flyCounter,flipCounter)).CompID == 4) + ...
             (LabeledFlyStruct.ExpNum(flyCounter).BehavData.OddFlips(LabelOrder(flyCounter,flipCounter)).CompID == 6) + ...
             (LabeledFlyStruct.ExpNum(flyCounter).BehavData.OddFlips(LabelOrder(flyCounter,flipCounter)).CompID == 8));
        GLM_Input_Struct(GLM_struct_counter).SinTwoTheta = ...
             sin(2*LabeledFlyStruct.ExpNum(flyCounter).BehavData.OddFlips(LabelOrder(flyCounter,flipCounter)).Orientation);
        GLM_Input_Struct(GLM_struct_counter).CosTwoTheta = ...
             cos(2*LabeledFlyStruct.ExpNum(flyCounter).BehavData.OddFlips(LabelOrder(flyCounter,flipCounter)).Orientation);
        GLM_Input_Struct(GLM_struct_counter).WidthOverHeight = ...
             LabeledFlyStruct.ExpNum(flyCounter).BehavData.OddFlips(LabelOrder(flyCounter,flipCounter)).BoundingBoxWidth ./ ...
             LabeledFlyStruct.ExpNum(flyCounter).BehavData.OddFlips(LabelOrder(flyCounter,flipCounter)).BoundingBoxHeight;
        GLM_Input_Struct(GLM_struct_counter).OffGlassYN = ...
             LabeledFlyStruct.ExpNum(flyCounter).BehavData.OddFlips(LabelOrder(flyCounter,flipCounter)).OffGlassYN;
         
        GLM_Input_Struct(GLM_struct_counter+1).Area = ...
             LabeledFlyStruct.ExpNum(flyCounter).BehavData.EvenFlips(LabelOrder(flyCounter+NumFlies,flipCounter)).Area;
        GLM_Input_Struct(GLM_struct_counter+1).CentroidX = ...
             LabeledFlyStruct.ExpNum(flyCounter).BehavData.EvenFlips(LabelOrder(flyCounter+NumFlies,flipCounter)).CentroidX - ...
             x_cent_corr_even(flyCounter);
        GLM_Input_Struct(GLM_struct_counter+1).CentroidY = ...
             LabeledFlyStruct.ExpNum(flyCounter).BehavData.EvenFlips(LabelOrder(flyCounter+NumFlies,flipCounter)).CentroidY - ...
             y_cent_corr_even(flyCounter);
        GLM_Input_Struct(GLM_struct_counter+1).BoundingBoxTLX = ...
             LabeledFlyStruct.ExpNum(flyCounter).BehavData.EvenFlips(LabelOrder(flyCounter+NumFlies,flipCounter)).BoundingBoxTLX - ...
             x_cent_corr_even(flyCounter);
        GLM_Input_Struct(GLM_struct_counter+1).BoundingBoxTLY = ...
             LabeledFlyStruct.ExpNum(flyCounter).BehavData.EvenFlips(LabelOrder(flyCounter+NumFlies,flipCounter)).BoundingBoxTLY - ...
             y_cent_corr_even(flyCounter);
        GLM_Input_Struct(GLM_struct_counter+1).BoundingBoxWidth = ...
             LabeledFlyStruct.ExpNum(flyCounter).BehavData.EvenFlips(LabelOrder(flyCounter+NumFlies,flipCounter)).BoundingBoxWidth;
        GLM_Input_Struct(GLM_struct_counter+1).BoundingBoxHeight = ...
             LabeledFlyStruct.ExpNum(flyCounter).BehavData.EvenFlips(LabelOrder(flyCounter+NumFlies,flipCounter)).BoundingBoxHeight;
        GLM_Input_Struct(GLM_struct_counter+1).MajorAxisLength = ...
             LabeledFlyStruct.ExpNum(flyCounter).BehavData.EvenFlips(LabelOrder(flyCounter+NumFlies,flipCounter)).MajorAxisLength;
        GLM_Input_Struct(GLM_struct_counter+1).MinorAxisLength = ...
             LabeledFlyStruct.ExpNum(flyCounter).BehavData.EvenFlips(LabelOrder(flyCounter+NumFlies,flipCounter)).MinorAxisLength;
        GLM_Input_Struct(GLM_struct_counter+1).Circularity = ...
             LabeledFlyStruct.ExpNum(flyCounter).BehavData.EvenFlips(LabelOrder(flyCounter+NumFlies,flipCounter)).Circularity;
        GLM_Input_Struct(GLM_struct_counter+1).Orientation = ...
             LabeledFlyStruct.ExpNum(flyCounter).BehavData.EvenFlips(LabelOrder(flyCounter+NumFlies,flipCounter)).Orientation;
        GLM_Input_Struct(GLM_struct_counter+1).VelX = ...
             LabeledFlyStruct.ExpNum(flyCounter).BehavData.EvenFlips(LabelOrder(flyCounter+NumFlies,flipCounter)).VelX;
        GLM_Input_Struct(GLM_struct_counter+1).VelY = ...
             LabeledFlyStruct.ExpNum(flyCounter).BehavData.EvenFlips(LabelOrder(flyCounter+NumFlies,flipCounter)).VelY;
        GLM_Input_Struct(GLM_struct_counter+1).Speed = ...
             LabeledFlyStruct.ExpNum(flyCounter).BehavData.EvenFlips(LabelOrder(flyCounter+NumFlies,flipCounter)).Speed;
        GLM_Input_Struct(GLM_struct_counter+1).AngularSpeed = ...
             LabeledFlyStruct.ExpNum(flyCounter).BehavData.EvenFlips(LabelOrder(flyCounter+NumFlies,flipCounter)).AngularSpeed;
        GLM_Input_Struct(GLM_struct_counter+1).InGapRegionYN = ...
             ((LabeledFlyStruct.ExpNum(flyCounter).BehavData.EvenFlips(LabelOrder(flyCounter+NumFlies,flipCounter)).CompID == 2) + ...
             (LabeledFlyStruct.ExpNum(flyCounter).BehavData.EvenFlips(LabelOrder(flyCounter+NumFlies,flipCounter)).CompID == 4) + ...
             (LabeledFlyStruct.ExpNum(flyCounter).BehavData.EvenFlips(LabelOrder(flyCounter+NumFlies,flipCounter)).CompID == 6) + ...
             (LabeledFlyStruct.ExpNum(flyCounter).BehavData.EvenFlips(LabelOrder(flyCounter+NumFlies,flipCounter)).CompID == 8));
        GLM_Input_Struct(GLM_struct_counter+1).SinTwoTheta = ...
             sin(2*LabeledFlyStruct.ExpNum(flyCounter).BehavData.EvenFlips(LabelOrder(flyCounter+NumFlies,flipCounter)).Orientation);
        GLM_Input_Struct(GLM_struct_counter+1).CosTwoTheta = ...
             cos(2*LabeledFlyStruct.ExpNum(flyCounter).BehavData.EvenFlips(LabelOrder(flyCounter+NumFlies,flipCounter)).Orientation);
        GLM_Input_Struct(GLM_struct_counter+1).WidthOverHeight = ...
             LabeledFlyStruct.ExpNum(flyCounter).BehavData.EvenFlips(LabelOrder(flyCounter+NumFlies,flipCounter)).BoundingBoxWidth ./ ...
             LabeledFlyStruct.ExpNum(flyCounter).BehavData.EvenFlips(LabelOrder(flyCounter+NumFlies,flipCounter)).BoundingBoxHeight;
        GLM_Input_Struct(GLM_struct_counter+1).OffGlassYN = ...
             LabeledFlyStruct.ExpNum(flyCounter).BehavData.EvenFlips(LabelOrder(flyCounter+NumFlies,flipCounter)).OffGlassYN;
        
        GLM_struct_counter = GLM_struct_counter + 2;
        
    end
end

GLM_Input_Struct_Zap = struct();
InputStructCounter = 1;
for InputStructCounterWZero = 1:length(GLM_Input_Struct)
    if length(GLM_Input_Struct(InputStructCounterWZero).Area) ~= 1
        GLM_Input_Struct_Zap(InputStructCounter).Area = GLM_Input_Struct(InputStructCounterWZero).Area(2:end);
        GLM_Input_Struct_Zap(InputStructCounter).CentroidX = GLM_Input_Struct(InputStructCounterWZero).CentroidX(2:end);
        GLM_Input_Struct_Zap(InputStructCounter).CentroidY = GLM_Input_Struct(InputStructCounterWZero).CentroidY(2:end);
        GLM_Input_Struct_Zap(InputStructCounter).BoundingBoxTLX = abs(GLM_Input_Struct(InputStructCounterWZero).BoundingBoxTLX(2:end));
        GLM_Input_Struct_Zap(InputStructCounter).BoundingBoxTLY = abs(GLM_Input_Struct(InputStructCounterWZero).BoundingBoxTLX(2:end));
        GLM_Input_Struct_Zap(InputStructCounter).BoundingBoxWidth = GLM_Input_Struct(InputStructCounterWZero).BoundingBoxWidth(2:end);
        GLM_Input_Struct_Zap(InputStructCounter).BoundingBoxHeight = GLM_Input_Struct(InputStructCounterWZero).BoundingBoxHeight(2:end);
        GLM_Input_Struct_Zap(InputStructCounter).MajorAxisLength = GLM_Input_Struct(InputStructCounterWZero).MajorAxisLength(2:end);
        GLM_Input_Struct_Zap(InputStructCounter).MinorAxisLength = GLM_Input_Struct(InputStructCounterWZero).MinorAxisLength(2:end);
        GLM_Input_Struct_Zap(InputStructCounter).Circularity = GLM_Input_Struct(InputStructCounterWZero).Circularity(2:end);
        GLM_Input_Struct_Zap(InputStructCounter).Orientation = abs(GLM_Input_Struct(InputStructCounterWZero).Orientation(2:end));
        GLM_Input_Struct_Zap(InputStructCounter).VelX = GLM_Input_Struct(InputStructCounterWZero).VelX;
        GLM_Input_Struct_Zap(InputStructCounter).VelY = GLM_Input_Struct(InputStructCounterWZero).VelY;
        GLM_Input_Struct_Zap(InputStructCounter).Speed = GLM_Input_Struct(InputStructCounterWZero).Speed;
        GLM_Input_Struct_Zap(InputStructCounter).AngularSpeed = GLM_Input_Struct(InputStructCounterWZero).AngularSpeed;
        GLM_Input_Struct_Zap(InputStructCounter).InGapRegionYN = GLM_Input_Struct(InputStructCounterWZero).InGapRegionYN(2:end);
        GLM_Input_Struct_Zap(InputStructCounter).SinTwoTheta = abs(GLM_Input_Struct(InputStructCounterWZero).SinTwoTheta(2:end));
        GLM_Input_Struct_Zap(InputStructCounter).CosTwoTheta = abs(GLM_Input_Struct(InputStructCounterWZero).CosTwoTheta(2:end));
        GLM_Input_Struct_Zap(InputStructCounter).WidthOverHeight = GLM_Input_Struct(InputStructCounterWZero).WidthOverHeight(2:end);
        GLM_Input_Struct_Zap(InputStructCounter).OffGlassYN = GLM_Input_Struct(InputStructCounterWZero).OffGlassYN(2:end);
        InputStructCounter = InputStructCounter + 1;
    end
end

numFrameBefAndAft = 0;
numSamples = 0;
for PostZapCounter = 1:length(GLM_Input_Struct_Zap)
    numSamples = numSamples + length(GLM_Input_Struct_Zap(PostZapCounter).Area) - 2*numFrameBefAndAft;
end

GLM_Input_Mat = zeros(numSamples, (length(fieldnames(GLM_Input_Struct_Zap))-1)*(2*numFrameBefAndAft+1));
GLM_Resp_Vec  = zeros(numSamples,1);

SampleNum = 1;
for PostZapCounter = 1:length(GLM_Input_Struct_Zap)
    for rollWindowStart = 1:(length(GLM_Input_Struct_Zap(PostZapCounter).Area)-2*numFrameBefAndAft)
        GLM_Input_Mat(SampleNum,(0*(2*numFrameBefAndAft+1)+1):(1*(2*numFrameBefAndAft+1))) = ...
            GLM_Input_Struct_Zap(PostZapCounter).Area((0*(2*numFrameBefAndAft+1)+rollWindowStart):(1*(2*numFrameBefAndAft+1)+rollWindowStart-1));
        GLM_Input_Mat(SampleNum,(1*(2*numFrameBefAndAft+1)+1):(2*(2*numFrameBefAndAft+1))) = ...
            GLM_Input_Struct_Zap(PostZapCounter).CentroidX((0*(2*numFrameBefAndAft+1)+rollWindowStart):(1*(2*numFrameBefAndAft+1)+rollWindowStart-1));
        GLM_Input_Mat(SampleNum,(2*(2*numFrameBefAndAft+1)+1):(3*(2*numFrameBefAndAft+1))) = ...
            GLM_Input_Struct_Zap(PostZapCounter).CentroidY((0*(2*numFrameBefAndAft+1)+rollWindowStart):(1*(2*numFrameBefAndAft+1)+rollWindowStart-1));
        GLM_Input_Mat(SampleNum,(3*(2*numFrameBefAndAft+1)+1):(4*(2*numFrameBefAndAft+1))) = ...
            GLM_Input_Struct_Zap(PostZapCounter).BoundingBoxTLX((0*(2*numFrameBefAndAft+1)+rollWindowStart):(1*(2*numFrameBefAndAft+1)+rollWindowStart-1));
        GLM_Input_Mat(SampleNum,(4*(2*numFrameBefAndAft+1)+1):(5*(2*numFrameBefAndAft+1))) = ...
            GLM_Input_Struct_Zap(PostZapCounter).BoundingBoxTLY((0*(2*numFrameBefAndAft+1)+rollWindowStart):(1*(2*numFrameBefAndAft+1)+rollWindowStart-1));
        GLM_Input_Mat(SampleNum,(5*(2*numFrameBefAndAft+1)+1):(6*(2*numFrameBefAndAft+1))) = ...
            GLM_Input_Struct_Zap(PostZapCounter).BoundingBoxWidth((0*(2*numFrameBefAndAft+1)+rollWindowStart):(1*(2*numFrameBefAndAft+1)+rollWindowStart-1));
        GLM_Input_Mat(SampleNum,(6*(2*numFrameBefAndAft+1)+1):(7*(2*numFrameBefAndAft+1))) = ...
            GLM_Input_Struct_Zap(PostZapCounter).BoundingBoxHeight((0*(2*numFrameBefAndAft+1)+rollWindowStart):(1*(2*numFrameBefAndAft+1)+rollWindowStart-1));
        GLM_Input_Mat(SampleNum,(7*(2*numFrameBefAndAft+1)+1):(8*(2*numFrameBefAndAft+1))) = ...
            GLM_Input_Struct_Zap(PostZapCounter).MajorAxisLength((0*(2*numFrameBefAndAft+1)+rollWindowStart):(1*(2*numFrameBefAndAft+1)+rollWindowStart-1));
        GLM_Input_Mat(SampleNum,(8*(2*numFrameBefAndAft+1)+1):(9*(2*numFrameBefAndAft+1))) = ...
            GLM_Input_Struct_Zap(PostZapCounter).MinorAxisLength((0*(2*numFrameBefAndAft+1)+rollWindowStart):(1*(2*numFrameBefAndAft+1)+rollWindowStart-1));
        GLM_Input_Mat(SampleNum,(9*(2*numFrameBefAndAft+1)+1):(10*(2*numFrameBefAndAft+1))) = ...
            GLM_Input_Struct_Zap(PostZapCounter).Circularity((0*(2*numFrameBefAndAft+1)+rollWindowStart):(1*(2*numFrameBefAndAft+1)+rollWindowStart-1));
        GLM_Input_Mat(SampleNum,(10*(2*numFrameBefAndAft+1)+1):(11*(2*numFrameBefAndAft+1))) = ...
            GLM_Input_Struct_Zap(PostZapCounter).Orientation((0*(2*numFrameBefAndAft+1)+rollWindowStart):(1*(2*numFrameBefAndAft+1)+rollWindowStart-1));
        GLM_Input_Mat(SampleNum,(11*(2*numFrameBefAndAft+1)+1):(12*(2*numFrameBefAndAft+1))) = ...
            GLM_Input_Struct_Zap(PostZapCounter).VelX((0*(2*numFrameBefAndAft+1)+rollWindowStart):(1*(2*numFrameBefAndAft+1)+rollWindowStart-1));
        GLM_Input_Mat(SampleNum,(12*(2*numFrameBefAndAft+1)+1):(13*(2*numFrameBefAndAft+1))) = ...
            GLM_Input_Struct_Zap(PostZapCounter).VelY((0*(2*numFrameBefAndAft+1)+rollWindowStart):(1*(2*numFrameBefAndAft+1)+rollWindowStart-1));
        GLM_Input_Mat(SampleNum,(13*(2*numFrameBefAndAft+1)+1):(14*(2*numFrameBefAndAft+1))) = ...
            GLM_Input_Struct_Zap(PostZapCounter).Speed((0*(2*numFrameBefAndAft+1)+rollWindowStart):(1*(2*numFrameBefAndAft+1)+rollWindowStart-1));
        GLM_Input_Mat(SampleNum,(14*(2*numFrameBefAndAft+1)+1):(15*(2*numFrameBefAndAft+1))) = ...
            GLM_Input_Struct_Zap(PostZapCounter).AngularSpeed((0*(2*numFrameBefAndAft+1)+rollWindowStart):(1*(2*numFrameBefAndAft+1)+rollWindowStart-1));
        GLM_Input_Mat(SampleNum,(15*(2*numFrameBefAndAft+1)+1):(16*(2*numFrameBefAndAft+1))) = ...
            GLM_Input_Struct_Zap(PostZapCounter).InGapRegionYN((0*(2*numFrameBefAndAft+1)+rollWindowStart):(1*(2*numFrameBefAndAft+1)+rollWindowStart-1));
        GLM_Input_Mat(SampleNum,(16*(2*numFrameBefAndAft+1)+1):(17*(2*numFrameBefAndAft+1))) = ...
            GLM_Input_Struct_Zap(PostZapCounter).SinTwoTheta((0*(2*numFrameBefAndAft+1)+rollWindowStart):(1*(2*numFrameBefAndAft+1)+rollWindowStart-1));
        GLM_Input_Mat(SampleNum,(17*(2*numFrameBefAndAft+1)+1):(18*(2*numFrameBefAndAft+1))) = ...
            GLM_Input_Struct_Zap(PostZapCounter).CosTwoTheta((0*(2*numFrameBefAndAft+1)+rollWindowStart):(1*(2*numFrameBefAndAft+1)+rollWindowStart-1));
        GLM_Input_Mat(SampleNum,(18*(2*numFrameBefAndAft+1)+1):(19*(2*numFrameBefAndAft+1))) = ...
            GLM_Input_Struct_Zap(PostZapCounter).WidthOverHeight((0*(2*numFrameBefAndAft+1)+rollWindowStart):(1*(2*numFrameBefAndAft+1)+rollWindowStart-1));
        GLM_Resp_Vec(SampleNum) = GLM_Input_Struct_Zap(PostZapCounter).OffGlassYN(rollWindowStart+numFrameBefAndAft);
        SampleNum = SampleNum + 1;
    end
end

GLM_Input_Mat = smoothdata(GLM_Input_Mat,1, 'gaussian', 5);

GLMrandOrder = randperm(length(GLM_Resp_Vec));
GLM_Input_Mat_Rand = zeros(size(GLM_Input_Mat));
GLM_Input_Mat_Rand(1:end,:) = GLM_Input_Mat(GLMrandOrder,:);
GLM_Resp_Vec_Rand = GLM_Resp_Vec(GLMrandOrder);

GLM_Input_Mat_Rand_Train = GLM_Input_Mat_Rand(1:floor(0.8*length(GLM_Resp_Vec)),:);
GLM_Input_Mat_Rand_Test  = GLM_Input_Mat_Rand((floor(0.8*length(GLM_Resp_Vec))+1):end,:);

GLM_Resp_Vec_Rand_Train = GLM_Resp_Vec_Rand(1:floor(0.8*length(GLM_Resp_Vec)));
GLM_Resp_Vec_Rand_Test  = GLM_Resp_Vec_Rand((floor(0.8*length(GLM_Resp_Vec))+1):end);