% Takes the finalFlyStruct and rearranges the data such that it separates
% out behavior data between flips to make it easier to manage
% Also computes derivatives of previously found values (e.g., VelX & VelY)

function WS = FlipBinner2(WS)

% function FlipBinnedFlyStruct = FlipBinner(finalFlyStruct)

% Port in the relevant fields from WS
finalFlyStruct = WS.finalFlyStruct;

% Declare FlipBinnedFlyStruct as a struct
FlipBinnedFlyStruct = struct();

for flyStructCounter = 1:length(finalFlyStruct)
    
    % FlipBinnedFlyStruct.BehavData
    for FlipCounter = 1:max(finalFlyStruct(flyStructCounter).FlipNumber)
        FlipLog = (finalFlyStruct(flyStructCounter).FlipNumber == FlipCounter);
        % Even flips
        if (-1)^(FlipCounter) == 1
            % Check that there is motion in the flip, and if not, input 0s
            if sum(FlipLog) == 0
                FlipBinnedFlyStruct.ExpNum(flyStructCounter).BehavData.EvenFlips(FlipCounter/2).Area = 0;
                FlipBinnedFlyStruct.ExpNum(flyStructCounter).BehavData.EvenFlips(FlipCounter/2).CentroidX = 0;
                FlipBinnedFlyStruct.ExpNum(flyStructCounter).BehavData.EvenFlips(FlipCounter/2).CentroidY = 0;
                FlipBinnedFlyStruct.ExpNum(flyStructCounter).BehavData.EvenFlips(FlipCounter/2).AbsoluteTime = 0;
                FlipBinnedFlyStruct.ExpNum(flyStructCounter).BehavData.EvenFlips(FlipCounter/2).FrameInFlip = 0;
                FlipBinnedFlyStruct.ExpNum(flyStructCounter).BehavData.EvenFlips(FlipCounter/2).BoundingBoxTLX = 0;
                FlipBinnedFlyStruct.ExpNum(flyStructCounter).BehavData.EvenFlips(FlipCounter/2).BoundingBoxTLY = 0;
                FlipBinnedFlyStruct.ExpNum(flyStructCounter).BehavData.EvenFlips(FlipCounter/2).BoundingBoxWidth = 0;
                FlipBinnedFlyStruct.ExpNum(flyStructCounter).BehavData.EvenFlips(FlipCounter/2).BoundingBoxHeight = 0;
                FlipBinnedFlyStruct.ExpNum(flyStructCounter).BehavData.EvenFlips(FlipCounter/2).MajorAxisLength = 0;
                FlipBinnedFlyStruct.ExpNum(flyStructCounter).BehavData.EvenFlips(FlipCounter/2).MinorAxisLength = 0;
                FlipBinnedFlyStruct.ExpNum(flyStructCounter).BehavData.EvenFlips(FlipCounter/2).Circularity = 0;
                FlipBinnedFlyStruct.ExpNum(flyStructCounter).BehavData.EvenFlips(FlipCounter/2).Orientation = 0;
                FlipBinnedFlyStruct.ExpNum(flyStructCounter).BehavData.EvenFlips(FlipCounter/2).VelX = 0;
                FlipBinnedFlyStruct.ExpNum(flyStructCounter).BehavData.EvenFlips(FlipCounter/2).VelY = 0;
                FlipBinnedFlyStruct.ExpNum(flyStructCounter).BehavData.EvenFlips(FlipCounter/2).Speed = 0;
                FlipBinnedFlyStruct.ExpNum(flyStructCounter).BehavData.EvenFlips(FlipCounter/2).AngularSpeed = 0;
                FlipBinnedFlyStruct.ExpNum(flyStructCounter).BehavData.EvenFlips(FlipCounter/2).CompID = 0;
            % If there is motion during the flip
            else
                FlipBinnedFlyStruct.ExpNum(flyStructCounter).BehavData.EvenFlips(FlipCounter/2).Area = ...
                    finalFlyStruct(flyStructCounter).Area(FlipLog);
                FlipBinnedFlyStruct.ExpNum(flyStructCounter).BehavData.EvenFlips(FlipCounter/2).CentroidX = ...
                    finalFlyStruct(flyStructCounter).CentroidX(FlipLog);
                FlipBinnedFlyStruct.ExpNum(flyStructCounter).BehavData.EvenFlips(FlipCounter/2).CentroidY = ...
                    finalFlyStruct(flyStructCounter).CentroidY(FlipLog);
                FlipBinnedFlyStruct.ExpNum(flyStructCounter).BehavData.EvenFlips(FlipCounter/2).AbsoluteTime = ...
                    finalFlyStruct(flyStructCounter).AbsoluteTime(FlipLog);
                FlipBinnedFlyStruct.ExpNum(flyStructCounter).BehavData.EvenFlips(FlipCounter/2).FrameInFlip = ...
                    finalFlyStruct(flyStructCounter).FrameInFlip(FlipLog);
                FlipBinnedFlyStruct.ExpNum(flyStructCounter).BehavData.EvenFlips(FlipCounter/2).BoundingBoxTLX = ...
                    finalFlyStruct(flyStructCounter).BoundingBoxTLX(FlipLog);
                FlipBinnedFlyStruct.ExpNum(flyStructCounter).BehavData.EvenFlips(FlipCounter/2).BoundingBoxTLY = ...
                    finalFlyStruct(flyStructCounter).BoundingBoxTLY(FlipLog);
                FlipBinnedFlyStruct.ExpNum(flyStructCounter).BehavData.EvenFlips(FlipCounter/2).BoundingBoxWidth = ...
                    finalFlyStruct(flyStructCounter).BoundingBoxWidth(FlipLog);
                FlipBinnedFlyStruct.ExpNum(flyStructCounter).BehavData.EvenFlips(FlipCounter/2).BoundingBoxHeight = ...
                    finalFlyStruct(flyStructCounter).BoundingBoxHeight(FlipLog);
                FlipBinnedFlyStruct.ExpNum(flyStructCounter).BehavData.EvenFlips(FlipCounter/2).MajorAxisLength = ...
                    finalFlyStruct(flyStructCounter).MajorAxisLength(FlipLog);
                FlipBinnedFlyStruct.ExpNum(flyStructCounter).BehavData.EvenFlips(FlipCounter/2).MinorAxisLength = ...
                    finalFlyStruct(flyStructCounter).MinorAxisLength(FlipLog);
                FlipBinnedFlyStruct.ExpNum(flyStructCounter).BehavData.EvenFlips(FlipCounter/2).Circularity = ...
                    finalFlyStruct(flyStructCounter).MinorAxisLength(FlipLog)./...
                    finalFlyStruct(flyStructCounter).MajorAxisLength(FlipLog);
                FlipBinnedFlyStruct.ExpNum(flyStructCounter).BehavData.EvenFlips(FlipCounter/2).Orientation = ...
                    finalFlyStruct(flyStructCounter).Orientation(FlipLog);
                FlipBinnedFlyStruct.ExpNum(flyStructCounter).BehavData.EvenFlips(FlipCounter/2).VelX = ...
                    diff(FlipBinnedFlyStruct.ExpNum(flyStructCounter).BehavData.EvenFlips(FlipCounter/2).CentroidX)...
                     ./diff(FlipBinnedFlyStruct.ExpNum(flyStructCounter).BehavData.EvenFlips(FlipCounter/2).AbsoluteTime);
                FlipBinnedFlyStruct.ExpNum(flyStructCounter).BehavData.EvenFlips(FlipCounter/2).VelY = ...
                    diff(FlipBinnedFlyStruct.ExpNum(flyStructCounter).BehavData.EvenFlips(FlipCounter/2).CentroidY)...
                     ./diff(FlipBinnedFlyStruct.ExpNum(flyStructCounter).BehavData.EvenFlips(FlipCounter/2).AbsoluteTime);
                FlipBinnedFlyStruct.ExpNum(flyStructCounter).BehavData.EvenFlips(FlipCounter/2).Speed = ...
                    sqrt((FlipBinnedFlyStruct.ExpNum(flyStructCounter).BehavData.EvenFlips(FlipCounter/2).VelX).^2 + ...
                         (FlipBinnedFlyStruct.ExpNum(flyStructCounter).BehavData.EvenFlips(FlipCounter/2).VelY).^2);
                % Must deal with the fact that theta goes from -90 to 90 and wraps around
                % Take the min of abs{[theta(i+1)-theta(i)], [mod(theta(i+1),180)-theta(i)], [mod(theta(i+1),180)-mod(theta(i),180)]}
                FlipBinnedFlyStruct.ExpNum(flyStructCounter).BehavData.EvenFlips(FlipCounter/2).AngularSpeed = ...
                    min(min(abs(diff(FlipBinnedFlyStruct.ExpNum(flyStructCounter).BehavData.EvenFlips(FlipCounter/2).Orientation)),...
                            abs(FlipBinnedFlyStruct.ExpNum(flyStructCounter).BehavData.EvenFlips(FlipCounter/2).Orientation(1:end-1)-...
                                mod(FlipBinnedFlyStruct.ExpNum(flyStructCounter).BehavData.EvenFlips(FlipCounter/2).Orientation(2:end),180))),...
                        abs(diff(mod(FlipBinnedFlyStruct.ExpNum(flyStructCounter).BehavData.EvenFlips(FlipCounter/2).Orientation,180))))...
                     ./diff(FlipBinnedFlyStruct.ExpNum(flyStructCounter).BehavData.EvenFlips(FlipCounter/2).AbsoluteTime);
                FlipBinnedFlyStruct.ExpNum(flyStructCounter).BehavData.EvenFlips(FlipCounter/2).CompID = ...
                    finalFlyStruct(flyStructCounter).CompID(FlipLog);
            end
        % Odd flips
        else
            % Check that there is motion in the flip, and if not, input 0s
            if sum(FlipLog) == 0
                FlipBinnedFlyStruct.ExpNum(flyStructCounter).BehavData.OddFlips((FlipCounter+1)/2).Area = 0;
                FlipBinnedFlyStruct.ExpNum(flyStructCounter).BehavData.OddFlips((FlipCounter+1)/2).CentroidX = 0;
                FlipBinnedFlyStruct.ExpNum(flyStructCounter).BehavData.OddFlips((FlipCounter+1)/2).CentroidY = 0;
                FlipBinnedFlyStruct.ExpNum(flyStructCounter).BehavData.OddFlips((FlipCounter+1)/2).AbsoluteTime = 0;
                FlipBinnedFlyStruct.ExpNum(flyStructCounter).BehavData.OddFlips((FlipCounter+1)/2).FrameInFlip = 0;
                FlipBinnedFlyStruct.ExpNum(flyStructCounter).BehavData.OddFlips((FlipCounter+1)/2).BoundingBoxTLX = 0;
                FlipBinnedFlyStruct.ExpNum(flyStructCounter).BehavData.OddFlips((FlipCounter+1)/2).BoundingBoxTLY = 0;
                FlipBinnedFlyStruct.ExpNum(flyStructCounter).BehavData.OddFlips((FlipCounter+1)/2).BoundingBoxWidth = 0;
                FlipBinnedFlyStruct.ExpNum(flyStructCounter).BehavData.OddFlips((FlipCounter+1)/2).BoundingBoxHeight = 0;
                FlipBinnedFlyStruct.ExpNum(flyStructCounter).BehavData.OddFlips((FlipCounter+1)/2).MajorAxisLength = 0;
                FlipBinnedFlyStruct.ExpNum(flyStructCounter).BehavData.OddFlips((FlipCounter+1)/2).MinorAxisLength = 0;
                FlipBinnedFlyStruct.ExpNum(flyStructCounter).BehavData.OddFlips((FlipCounter+1)/2).Circularity = 0;
                FlipBinnedFlyStruct.ExpNum(flyStructCounter).BehavData.OddFlips((FlipCounter+1)/2).Orientation = 0;
                FlipBinnedFlyStruct.ExpNum(flyStructCounter).BehavData.OddFlips((FlipCounter+1)/2).VelX = 0;
                FlipBinnedFlyStruct.ExpNum(flyStructCounter).BehavData.OddFlips((FlipCounter+1)/2).VelY = 0;
                FlipBinnedFlyStruct.ExpNum(flyStructCounter).BehavData.OddFlips((FlipCounter+1)/2).Speed = 0;
                FlipBinnedFlyStruct.ExpNum(flyStructCounter).BehavData.OddFlips((FlipCounter+1)/2).AngularSpeed = 0;
                FlipBinnedFlyStruct.ExpNum(flyStructCounter).BehavData.OddFlips((FlipCounter+1)/2).CompID = 0;
            % If there is motion during the flip
            else
                FlipBinnedFlyStruct.ExpNum(flyStructCounter).BehavData.OddFlips((FlipCounter+1)/2).Area = ...
                    finalFlyStruct(flyStructCounter).Area(FlipLog);
                FlipBinnedFlyStruct.ExpNum(flyStructCounter).BehavData.OddFlips((FlipCounter+1)/2).CentroidX = ...
                    finalFlyStruct(flyStructCounter).CentroidX(FlipLog);
                FlipBinnedFlyStruct.ExpNum(flyStructCounter).BehavData.OddFlips((FlipCounter+1)/2).CentroidY = ...
                    finalFlyStruct(flyStructCounter).CentroidY(FlipLog);
                FlipBinnedFlyStruct.ExpNum(flyStructCounter).BehavData.OddFlips((FlipCounter+1)/2).AbsoluteTime = ...
                    finalFlyStruct(flyStructCounter).AbsoluteTime(FlipLog);
                FlipBinnedFlyStruct.ExpNum(flyStructCounter).BehavData.OddFlips((FlipCounter+1)/2).FrameInFlip = ...
                    finalFlyStruct(flyStructCounter).FrameInFlip(FlipLog);
                FlipBinnedFlyStruct.ExpNum(flyStructCounter).BehavData.OddFlips((FlipCounter+1)/2).BoundingBoxTLX = ...
                    finalFlyStruct(flyStructCounter).BoundingBoxTLX(FlipLog);
                FlipBinnedFlyStruct.ExpNum(flyStructCounter).BehavData.OddFlips((FlipCounter+1)/2).BoundingBoxTLY = ...
                    finalFlyStruct(flyStructCounter).BoundingBoxTLY(FlipLog);
                FlipBinnedFlyStruct.ExpNum(flyStructCounter).BehavData.OddFlips((FlipCounter+1)/2).BoundingBoxWidth = ...
                    finalFlyStruct(flyStructCounter).BoundingBoxWidth(FlipLog);
                FlipBinnedFlyStruct.ExpNum(flyStructCounter).BehavData.OddFlips((FlipCounter+1)/2).BoundingBoxHeight = ...
                    finalFlyStruct(flyStructCounter).BoundingBoxHeight(FlipLog);
                FlipBinnedFlyStruct.ExpNum(flyStructCounter).BehavData.OddFlips((FlipCounter+1)/2).MajorAxisLength = ...
                    finalFlyStruct(flyStructCounter).MajorAxisLength(FlipLog);
                FlipBinnedFlyStruct.ExpNum(flyStructCounter).BehavData.OddFlips((FlipCounter+1)/2).MinorAxisLength = ...
                    finalFlyStruct(flyStructCounter).MinorAxisLength(FlipLog);
                FlipBinnedFlyStruct.ExpNum(flyStructCounter).BehavData.OddFlips((FlipCounter+1)/2).Circularity = ...
                    finalFlyStruct(flyStructCounter).MinorAxisLength(FlipLog)./...
                    finalFlyStruct(flyStructCounter).MajorAxisLength(FlipLog);
                FlipBinnedFlyStruct.ExpNum(flyStructCounter).BehavData.OddFlips((FlipCounter+1)/2).Orientation = ...
                    finalFlyStruct(flyStructCounter).Orientation(FlipLog);
                FlipBinnedFlyStruct.ExpNum(flyStructCounter).BehavData.OddFlips((FlipCounter+1)/2).VelX = ...
                    diff(FlipBinnedFlyStruct.ExpNum(flyStructCounter).BehavData.OddFlips((FlipCounter+1)/2).CentroidX)...
                     ./diff(FlipBinnedFlyStruct.ExpNum(flyStructCounter).BehavData.OddFlips((FlipCounter+1)/2).AbsoluteTime);
                FlipBinnedFlyStruct.ExpNum(flyStructCounter).BehavData.OddFlips((FlipCounter+1)/2).VelY = ...
                    diff(FlipBinnedFlyStruct.ExpNum(flyStructCounter).BehavData.OddFlips((FlipCounter+1)/2).CentroidY)...
                     ./diff(FlipBinnedFlyStruct.ExpNum(flyStructCounter).BehavData.OddFlips((FlipCounter+1)/2).AbsoluteTime);
                FlipBinnedFlyStruct.ExpNum(flyStructCounter).BehavData.OddFlips((FlipCounter+1)/2).Speed = ...
                    sqrt((FlipBinnedFlyStruct.ExpNum(flyStructCounter).BehavData.OddFlips((FlipCounter+1)/2).VelX).^2 + ...
                         (FlipBinnedFlyStruct.ExpNum(flyStructCounter).BehavData.OddFlips((FlipCounter+1)/2).VelY).^2);
                % Must deal with the fact that theta goes from -90 to 90 and wraps around
                % Take the min of abs{[theta(i+1)-theta(i)], [mod(theta(i+1),180)-theta(i)], [mod(theta(i+1),180)-mod(theta(i),180)]}
                FlipBinnedFlyStruct.ExpNum(flyStructCounter).BehavData.OddFlips((FlipCounter+1)/2).AngularSpeed = ...
                    min(min(abs(diff(FlipBinnedFlyStruct.ExpNum(flyStructCounter).BehavData.OddFlips((FlipCounter+1)/2).Orientation)),...
                            abs(FlipBinnedFlyStruct.ExpNum(flyStructCounter).BehavData.OddFlips((FlipCounter+1)/2).Orientation(1:end-1)-...
                                mod(FlipBinnedFlyStruct.ExpNum(flyStructCounter).BehavData.OddFlips((FlipCounter+1)/2).Orientation(2:end),180))),...
                        abs(diff(mod(FlipBinnedFlyStruct.ExpNum(flyStructCounter).BehavData.OddFlips((FlipCounter+1)/2).Orientation,180))))...
                     ./diff(FlipBinnedFlyStruct.ExpNum(flyStructCounter).BehavData.OddFlips((FlipCounter+1)/2).AbsoluteTime);
                FlipBinnedFlyStruct.ExpNum(flyStructCounter).BehavData.OddFlips((FlipCounter+1)/2).CompID = ...
                    finalFlyStruct(flyStructCounter).CompID(FlipLog);
            end
        end
    end
    
    % FlipBinnedFlyStruct.IdData
    FlipBinnedFlyStruct.ExpNum(flyStructCounter).IdData.ExpNum = ...
        finalFlyStruct(flyStructCounter).ExpNum;
    FlipBinnedFlyStruct.ExpNum(flyStructCounter).IdData.CorridorID = ...
        finalFlyStruct(flyStructCounter).CorridorID;
    FlipBinnedFlyStruct.ExpNum(flyStructCounter).IdData.LocOfSmallestGapInOddFlip = ...
        finalFlyStruct(flyStructCounter).LocOfSmallestGapInOddFlip;
    
    % FlipBinnedFlyStruct.Metadata
    FlipBinnedFlyStruct.ExpNum(flyStructCounter).MetaData.DirectoryName = ...
        finalFlyStruct(flyStructCounter).DirectoryName;
    FlipBinnedFlyStruct.ExpNum(flyStructCounter).MetaData.Genotype = ...
        finalFlyStruct(flyStructCounter).Genotype;
    FlipBinnedFlyStruct.ExpNum(flyStructCounter).MetaData.VidFile = ...
        finalFlyStruct(flyStructCounter).VidFile;
    FlipBinnedFlyStruct.ExpNum(flyStructCounter).MetaData.DateAcq = ...
        finalFlyStruct(flyStructCounter).DateAcq;
    FlipBinnedFlyStruct.ExpNum(flyStructCounter).MetaData.TimeAcq = ...
        finalFlyStruct(flyStructCounter).TimeAcq;
    FlipBinnedFlyStruct.ExpNum(flyStructCounter).MetaData.EclosionDate = ...
        finalFlyStruct(flyStructCounter).EclosionDate;
    FlipBinnedFlyStruct.ExpNum(flyStructCounter).MetaData.TimeZone = ...
        finalFlyStruct(flyStructCounter).TimeZone;
    FlipBinnedFlyStruct.ExpNum(flyStructCounter).MetaData.FlipRate = ...
        finalFlyStruct(flyStructCounter).FlipRate;
    FlipBinnedFlyStruct.ExpNum(flyStructCounter).MetaData.ExpLength = ...
        finalFlyStruct(flyStructCounter).ExpLength;
    FlipBinnedFlyStruct.ExpNum(flyStructCounter).MetaData.Temperature = ...
        finalFlyStruct(flyStructCounter).Temperature;
    FlipBinnedFlyStruct.ExpNum(flyStructCounter).MetaData.SizeThreshCutOff = ...
        finalFlyStruct(flyStructCounter).SizeThreshCutOff;
    FlipBinnedFlyStruct.ExpNum(flyStructCounter).MetaData.IndPosFrameBuffer = ...
        finalFlyStruct(flyStructCounter).IndPosFrameBuffer;
    FlipBinnedFlyStruct.ExpNum(flyStructCounter).MetaData.Notes = ...
        finalFlyStruct(flyStructCounter).Notes;
end

% Update the fields in WS
WS.FlipBinnedFlyStruct = FlipBinnedFlyStruct;

end