function pValues = RunCrossingComparisonStatistics()

% Have the user select the folders they want to compare (1 experimental
% folder and 2 control folders)
WS_exp_folderPath = uigetdir('C:\Users\clarklab\Joe\Gap_Crossing\Data', ...
                                  'Select experimental group folder' );
WS_ctrl_1_folderPath = uigetdir('C:\Users\clarklab\Joe\Gap_Crossing\Data', ...
                                  'Select control group 1 folder' );
WS_ctrl_2_folderPath = uigetdir('C:\Users\clarklab\Joe\Gap_Crossing\Data', ...
                                  'Select control group 2 folder' );

% Now load in the files
WS_exp = load([WS_exp_folderPath, '\', ...
             erase(WS_exp_folderPath,'C:\Users\clarklab\Joe\Gap_Crossing\Data\'), ...
             '_WS_Combined.mat']);
WS_ctrl_1 = load([WS_ctrl_1_folderPath, '\', ...
             erase(WS_ctrl_1_folderPath,'C:\Users\clarklab\Joe\Gap_Crossing\Data\'), ...
             '_WS_Combined.mat']);
WS_ctrl_2 = load([WS_ctrl_2_folderPath, '\', ...
             erase(WS_ctrl_2_folderPath,'C:\Users\clarklab\Joe\Gap_Crossing\Data\'), ...
             '_WS_Combined.mat']);

% Remove the extra layer of WS that's problematic when using load above
WS_exp = WS_exp.WS;
WS_ctrl_1 = WS_ctrl_1.WS;
WS_ctrl_2 = WS_ctrl_2.WS;

% Initialize matrix that holds the p-values
pValues = zeros(WS_exp.NumGaps,2);

% Now go through and run an unpaired t-test between the experiments
for gapCounter = 1:WS_exp.NumGaps
    % Compare the experimental data to control 1
    pValues(gapCounter,1) = ...
        ranksum(WS_exp.crossStats.AllAllVecProperCrossOverAllGapEventRate(:,gapCounter), ...
                WS_ctrl_1.crossStats.AllAllVecProperCrossOverAllGapEventRate(:,gapCounter));
    % Compare the experimental data to control 2
    pValues(gapCounter,2) = ...
        ranksum(WS_exp.crossStats.AllAllVecProperCrossOverAllGapEventRate(:,gapCounter), ...
                WS_ctrl_2.crossStats.AllAllVecProperCrossOverAllGapEventRate(:,gapCounter));
end

end