figure

genotype = 28;
controlGenotype = 23;

% Construct the synthetic controls (this is a model where the effect of
% each construct [UAS and Gal4] have an individual additive effect)
% The mean of the synthetic control algebraically simplifies to <Gal4/+> + <UAS/+> - <+> 
synth_mean = ...
    mean(AllCrossStats{genotype,3}.AllUpVecProperCrossOverAllGapEventRate) + ...
    mean(AllCrossStats{controlGenotype,1}.AllUpVecProperCrossOverAllGapEventRate) - ...
    mean(AllCrossStats{1,1}.AllUpVecProperCrossOverAllGapEventRate);
% Ensure that the crossing probability is non-negative
synth_mean = synth_mean.*(synth_mean>=0);
% The error of the synthetic control is computed via error propogation
synth_sem = sqrt(...
    (AllCrossStats{genotype,3}.AllUpVecProperCrossOverAllGapEventStd).^2 + ...
    (AllCrossStats{controlGenotype,1}.AllUpVecProperCrossOverAllGapEventStd).^2 + ...
    (AllCrossStats{1,1}.AllUpVecProperCrossOverAllGapEventStd).^2);

% Gal4 > + control (gray)
hold on
errorbar(1:0.5:2.5,...
         mean(AllCrossStats{genotype,3}.AllUpVecProperCrossOverAllGapEventRate),...
         AllCrossStats{genotype,3}.AllUpVecProperCrossOverAllGapEventStd,...
         'Color',[.7 .7 .7],'CapSize',0,'LineWidth',3,'Marker','o','MarkerSize',3,'MarkerFaceColor','auto','LineStyle','none');
plot(1:0.5:2.5,...
         mean(AllCrossStats{genotype,3}.AllUpVecProperCrossOverAllGapEventRate),'Color',[.7 .7 .7])
% sp empty (DBD) > shts control (solid black)
errorbar(1:0.5:2.5,...
         mean(AllCrossStats{controlGenotype,1}.AllUpVecProperCrossOverAllGapEventRate),...
         AllCrossStats{controlGenotype,1}.AllUpVecProperCrossOverAllGapEventStd,...
         'k','CapSize',0,'LineWidth',3,'Marker','o','MarkerSize',3,'MarkerFaceColor','auto','LineStyle','none');
plot(1:0.5:2.5,...
         mean(AllCrossStats{controlGenotype,1}.AllUpVecProperCrossOverAllGapEventRate),'k')
% Synthetic control (dashed black)
errorbar(1:0.5:2.5,...
         synth_mean,...
         synth_sem,...
         'k','CapSize',0,'LineWidth',3,'Marker','o','MarkerSize',3,'MarkerFaceColor','auto','LineStyle','none');
plot(1:0.5:2.5,...
         synth_mean,'k--')

% Plot the silencing experiment in red on the same plot as control(s)
errorbar(1:0.5:2.5,...
         mean(AllCrossStats{genotype,4}.AllUpVecProperCrossOverAllGapEventRate),...
         AllCrossStats{genotype,4}.AllUpVecProperCrossOverAllGapEventStd,...
         'r','CapSize',0,'LineWidth',3,'Marker','o','MarkerSize',3,'MarkerFaceColor','auto','LineStyle','none');
plot(1:0.5:2.5,...
         mean(AllCrossStats{genotype,4}.AllUpVecProperCrossOverAllGapEventRate),'r')
hold off

hold on
h1 = ...
    plot(1,nan(1,1),'Color','r','Marker','none','LineWidth',5);
h2 = ...
    plot(1,nan(1,1),'Color',[.7 .7 .7],'Marker','none','LineWidth',5);
h3 = ...
    plot(1,nan(1,1),'Color','k','Marker','none','LineWidth',5);
h4 = ...
    plot(1,nan(1,1),'k--','Marker','none','LineWidth',5);
lg  = legend([h1 h2 h3 h4],{'[Neuron] > +;sh^{ts};shR', ...
             '[Neuron] > +;+;+',...
             'split empty (DBD) > +;sh^{ts};shR',...
             'synthetic control'},'AutoUpdate','off'); 
lg.FontSize = 10;
hold off

ylim([0,1]);
xlim([0.8,2.7]);
xticks([]);
yticks([0,1]);
ylabel('Crossing Probability')